# Generated by Django 3.2.3 on 2021-12-22 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('full_path', models.TextField()),
                ('header', models.JSONField()),
                ('content', models.JSONField()),
                ('method', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('traceback', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_datetime',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('full_path', models.TextField()),
                ('header', models.JSONField()),
                ('content', models.JSONField()),
                ('method', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_datetime',),
                'abstract': False,
            },
        ),
    ]
