# Generated by Django 3.2.3 on 2021-11-22 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField()),
                ('full_path', models.TextField()),
                ('request_header', models.JSONField()),
                ('request_content', models.JSONField()),
                ('request_type', models.TextField()),
                ('traceback', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_error', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_datetime',),
            },
        ),
    ]
